source 'https://rubygems.org'

gem 'rails', '4.2.4'

gem 'bootstrap-sass'
gem 'bootswatch-rails'
gem 'coffee-rails'
gem 'devise'
gem 'dotenv-rails'
gem 'exception_notification'
gem 'faraday'
gem 'font-awesome-rails'
gem 'foreman'
gem 'google-analytics-rails'
gem 'hamlit'
gem 'jbuilder'
gem 'jquery-rails'
gem 'kaminari'
gem 'mysql2'
gem 'newrelic_rpm', '3.9.5.251'
gem 'octokit'
gem 'omniauth'
gem 'omniauth-github'
gem 'progress_bar'
gem 'rack-user_agent'
gem 'redis-rails'
gem 'sass-rails'
gem 'therubyracer'
gem 'uglifier'
gem 'unicorn'

gem 'ridgepole'

group :development, :test do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-sidekiq'
  gem 'capistrano3-unicorn'
  gem 'factory_girl'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'silencer'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'timecop'
  gem 'rack_session_access'
end
