default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: fukuro_development

test:
  <<: *default
  database: fukuro_test

production:
  <<: *default
  database: fukuro_production
